version: '3'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - ./media:/app/media
      - ./static:/app/static  
    ports:
      - "80:80"
      #- "8000:8000"
    depends_on:
      - db
    # Add other configuration for your web service

  db:
    image: postgres:16.0  # Use the PostgreSQL image from Docker Hub
    environment:
      POSTGRES_DB: "ShopOnlineDB"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "Pass@99"
    ports:
      - "5432:5432"
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
    # Add other configuration for your PostgreSQL container

#volumes:
  #postgres_data:  # Define a named volume for PostgreSQL data
