FROM python:3.7

WORKDIR /app
COPY requirements.txt .
#RUN pip install -r requirements.txt
RUN pip install --no-cache-dir -r requirements.txt

#RUN apt update
#RUN apt install -y nginx
#
#RUN rm /etc/nginx/sites-available/default
#
#COPY scripts/default.conf /etc/nginx/sites-available/default
# Install Nginx and remove the default configuration
RUN apt-get update && \
    apt-get install -y nginx && \
    rm /etc/nginx/sites-available/default

 #Copy your custom Nginx configuration
COPY scripts/default.conf /etc/nginx/sites-available/default



COPY . .

RUN chmod +x ./entrypoint.sh


#CMD /bin/sh -c "./entrypoint.sh && nginx -g 'daemon off;' & python manage.py runserver 0.0.0.0:8000"
#CMD /bin/sh -c "./entrypoint.sh && nginx -g 'daemon off;' & gunicorn -w 4 -b 0.0.0.0:8000 ShopOnline.wsgi:application"
CMD /bin/sh -c "./entrypoint.sh && nginx -g 'daemon off;' & gunicorn ShopOnline.wsgi:application --bind 0.0.0.0:8000"


