# Generated by Django 4.2.5 on 2023-12-25 11:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('App_Products', '0004_product_color_product_size'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='color',
        ),
        migrations.RemoveField(
            model_name='product',
            name='size',
        ),
        migrations.CreateModel(
            name='Product_Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='Products')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='image_variants', to='App_Products.product')),
            ],
        ),
    ]
