# Generated by Django 4.2.5 on 2024-01-02 16:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('App_Products', '0005_remove_product_color_remove_product_size_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product_size',
            name='size',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_size', to='App_Products.size'),
        ),
    ]
