# Generated by Django 3.2.23 on 2024-02-11 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_Products', '0006_alter_product_size_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='preview_text',
            field=models.TextField(max_length=400, verbose_name='Preview Text'),
        ),
    ]
