# Generated by Django 3.2.23 on 2024-06-25 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_Home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('address', models.CharField(max_length=255)),
                ('services', models.CharField(choices=[('Architecture', 'Architecture'), ('The Rehearsal Dinner', 'The Rehearsal Dinner'), ('The Afterparty', 'The Afterparty'), ('Videographers', 'Videographers'), ('Perfect Cake', 'Perfect Cake'), ('All Of The Above', 'All Of The Above')], default='Architecture', max_length=50, unique=True)),
                ('phone', models.CharField(max_length=15)),
                ('subject', models.CharField(max_length=100)),
                ('message', models.TextField(blank=True, max_length=264)),
            ],
        ),
    ]
