# Generated by Django 3.2.23 on 2024-06-27 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_Home', '0002_contactus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactus',
            name='services',
            field=models.CharField(choices=[('Architecture', 'Architecture'), ('The Rehearsal Dinner', 'The Rehearsal Dinner'), ('The Afterparty', 'The Afterparty'), ('Videographers', 'Videographers'), ('Perfect Cake', 'Perfect Cake'), ('All Of The Above', 'All Of The Above')], default='Architecture', max_length=80),
        ),
    ]
